services:
    mongo:
        image: mongo:latest
        container_name: mongodb-dev
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: Prolink
        volumes:
            - mongo-data:/data/db
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
    mongo-data:
        driver: local
